"""
SQL Generator — assembles SQL from skills YAMLs.
"""
from skills_loader import load_all

def generate_sql(report_id: str, slicer_values: dict = None) -> str:
    data = load_all()
    report = data["reports"].get(report_id)
    if not report:
        return f"-- ERROR: Report '{report_id}' not found"

    domain = data["domain"]
    joins = data["joins"]
    templates = domain.get("field_templates", {})
    slicer_values = slicer_values or {}

    lines = []
    lines.append(f"-- ============================================")
    lines.append(f"-- {report['report_name']}")
    lines.append(f"-- Generated by SQL Validator")
    lines.append(f"-- Slicers: {slicer_values or 'None'}")
    lines.append(f"-- ============================================")
    lines.append("")

    # CTE 1: base_data with deduplication
    lines.append("WITH base_data AS (")
    lines.append("    SELECT")

    # Select columns from field templates
    select_cols = []
    for field in report["fields"]:
        tref = field.get("template_ref", "")
        tmpl = templates.get(tref, {})
        expr = tmpl.get("sql_expression", "")

        # Expand complex field references
        if expr.startswith("compliance_calculation"):
            expr = """CASE
            WHEN M.NCQAInvertedFlag = 'Y' THEN
                ROUND(SUM(F.Act_Performance_Not_Met) * 100.0
                    / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0), 2)
            ELSE
                ROUND(SUM(F.Act_Performance_Met) * 100.0
                    / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0), 2)
        END"""
        elif expr.startswith("percentile_calculation"):
            expr = """CASE
            WHEN NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) IS NULL THEN NULL
            WHEN QC.Cutpoint3 = 0 AND QC.Cutpoint5 = 0 AND QC.Cutpoint7 = 0 AND QC.Cutpoint8 = 0 THEN NULL
            ELSE CASE
                WHEN M.NCQAInvertedFlag = 'Y' THEN
                    CASE
                        WHEN (SUM(F.Act_Performance_Not_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint3 THEN '<25th'
                        WHEN (SUM(F.Act_Performance_Not_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint5 THEN '25th'
                        WHEN (SUM(F.Act_Performance_Not_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint7 THEN '50th'
                        WHEN (SUM(F.Act_Performance_Not_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint8 THEN '75th'
                        ELSE '90th'
                    END
                ELSE
                    CASE
                        WHEN (SUM(F.Act_Performance_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint3 THEN '<25th'
                        WHEN (SUM(F.Act_Performance_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint5 THEN '25th'
                        WHEN (SUM(F.Act_Performance_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint7 THEN '50th'
                        WHEN (SUM(F.Act_Performance_Met) * 100.0) / NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) < QC.Cutpoint8 THEN '75th'
                        ELSE '90th'
                    END
                END
        END"""
        elif expr.startswith("gap_to_percentile"):
            cutpoint = expr.split("(")[1].rstrip(")")
            expr = f"""CASE
            WHEN M.NCQAInvertedFlag = 'Y' THEN
                CASE WHEN CEIL((NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) * QC.{cutpoint} / 100) - SUM(F.Act_Performance_Not_Met)) <= 0 THEN NULL
                     ELSE CEIL((NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) * QC.{cutpoint} / 100) - SUM(F.Act_Performance_Not_Met)) END
            ELSE
                CASE WHEN CEIL((NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) * QC.{cutpoint} / 100) - SUM(F.Act_Performance_Met)) <= 0 THEN NULL
                     ELSE CEIL((NULLIF(SUM(F.Act_Performance_Met) + SUM(F.Act_Performance_Not_Met), 0) * QC.{cutpoint} / 100) - SUM(F.Act_Performance_Met)) END
        END"""
        elif expr.startswith("clinical_status_count"):
            codes = expr.split("(")[1].rstrip(")").split(",")
            codes = [c.strip() for c in codes]
            entity_cases = []
            for etype, ecol in [("Visit", "visitSSUI"), ("Event", "eventSSUI"), ("Patient-Process", "patientSSUI")]:
                if len(codes) == 1:
                    entity_cases.append(f"WHEN M.measuretype = '{etype}' THEN COUNT(CASE WHEN F.clinicalonlystatus = {codes[0]} THEN F.{ecol} END)")
                else:
                    entity_cases.append(f"WHEN M.measuretype = '{etype}' THEN COUNT(CASE WHEN F.clinicalonlystatus IN ({','.join(codes)}) THEN F.{ecol} END) - COUNT(CASE WHEN F.clinicalonlystatus = {codes[-1]} THEN F.{ecol} END)")
            expr = "CASE\n            " + "\n            ".join(entity_cases) + "\n        END"

        if not expr:
            expr = f"-- TODO: {field['display_name']}"

        if "\n" in expr:
            indented = expr.strip().replace("\n", "\n        ")
            select_cols.append(f"        {indented}\n            AS [{field['display_name']}]")
        else:
            select_cols.append(f"        {expr.strip()} AS [{field['display_name']}]")

    lines.append(",\n".join(select_cols))

    # Deduplication
    dedup = report.get("deduplication")
    if dedup:
        part = ", ".join(dedup["partition_by"])
        lines.append(f",\n        ROW_NUMBER() OVER (PARTITION BY {part} ORDER BY {dedup['order_by']}) AS RN")

    # FROM + JOINs
    lines.append("")
    lines.append(f"    FROM {report['base_table']} F")
    for join_ref in report.get("uses_joins", []):
        j = joins.get(join_ref, {})
        sql = j.get("sql", "")
        if sql:
            for jline in sql.strip().split("\n"):
                lines.append(f"    {jline}")

    # WHERE — fixed filters
    lines.append("")
    lines.append("    WHERE")
    fixed = report.get("fixed_filters", [])
    for i, filt in enumerate(fixed):
        prefix = "        " if i == 0 else "        AND "
        lines.append(f"{prefix}{filt}")

    # WHERE — slicer values
    std_slicers = domain.get("standard_slicers", [])
    slicer_map = {s["name"]: s for s in std_slicers}
    for slicer_def in report.get("slicers", []):
        sname = slicer_def["name"]
        val = slicer_values.get(sname, "")
        sinfo = slicer_map.get(sname, {})
        col = sinfo.get("column", "")
        if val and val.lower() not in ("all", "all (no slicer)", ""):
            lines.append(f"        AND {col} = '{val}'")

    lines.append(")")
    lines.append("")

    # Final SELECT
    field_names = [f"[{f['display_name']}]" for f in report["fields"]]
    lines.append("SELECT")
    lines.append("    " + ",\n    ".join(field_names))
    lines.append("FROM base_data")
    if dedup:
        lines.append(f"WHERE {dedup['filter']}")

    # ORDER BY
    sort = report.get("sort_by", [])
    if sort:
        sort_parts = [f"{s['column']} {s['direction']}" for s in sorted(sort, key=lambda x: x["priority"])]
        lines.append(f"ORDER BY {', '.join(sort_parts)}")

    lines.append(";")
    return "\n".join(lines)
